# Generated by Django 5.2.3 on 2025-06-27 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_username', models.CharField(max_length=80, unique=True)),
                ('access_token', models.CharField(max_length=256)),
                ('refresh_token', models.CharField(blank=True, max_length=256, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_post_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('media_url', models.URLField(blank=True, max_length=500, null=True)),
                ('post_type', models.CharField(blank=True, max_length=50, null=True)),
                ('original_subreddit', models.CharField(max_length=100)),
                ('created_utc', models.DateTimeField()),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('reddit_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='reddit_scheduler.redditaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubredditSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_subreddits', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subreddit_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
