# Generated by Django 5.2.3 on 2025-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Your Reddit Application Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Your Reddit Application Client Secret', max_length=255)),
                ('redirect_uri', models.URLField(help_text='The Redirect URI configured in your Reddit App (e.g., [http://127.0.0.1:8000/reddit/callback/](http://127.0.0.1:8000/reddit/callback/))', max_length=500)),
            ],
            options={
                'verbose_name': 'Reddit API Settings',
                'verbose_name_plural': 'Reddit API Settings',
            },
        ),
    ]
